title: Wi1k1n's website
description: My name is Ilya Mazlov. Feel free to contact me if you have any questions.
logo: assets/img/avatar.jpg
show_downloads: false
google_analytics: true

thingiverse: https://www.thingiverse.com/wi1k1n

theme: jekyll-theme-minimal